### ISSUE TITLE
Nonlinear version of R^2regresssort

### ISSUE THREAD

**Issue by MingjiaLi666** [CausalDisco/CausalDisco#3]
Hi, I'm looking for a nonlinear version of r^2sortnregress, can you provide some insight? I'm currently struggling with how to determine the coefficient when using a nonlinear regressor.

**Comment by Scriddie** [comment]
Hi @MingjiaLi666,

The library doesn't contain a ready-to-use implementation of nonlinear R², since we felt that the nonlinear case would require additional investigation beyond the scope of [the paper](https://arxiv.org/pdf/2303.18211). For example, emerging patterns in R² may depend on the type and variety of functions used, and estimating R² empirically requires an appropriate choice of regressor.
Nonetheless, programmatically an extension to nonlinear regression is not difficult and may well be worth trying. You could simply adapt the `r2coeff` method to make the `except` block in [analytics.py](https://github.com/CausalDisco/CausalDisco/blob/main/CausalDisco/analytics.py#L59) the default, and replace the linear regression with a nonlinear regressor.

Let me know if you have any further questions :)

**Comment by MingjiaLi666** [comment]
Thanks for your attention and reply! I'm tring to apply ridge regression with RBF kernel (other kernels maybe also OK) to replace the linear regression, where the linear coefficient is replaced by dual coefficient. Something looks like this
![image](https://github.com/CausalDisco/CausalDisco/assets/44083574/6543d99f-96d8-4ce9-b761-75f9dd2fa7d6)
I don's this is proper way but the result on Erdos random graph with 10 node 20 edges with mlp nonlinear causal relation looks not bad 
![image](https://github.com/CausalDisco/CausalDisco/assets/44083574/85441fa9-302b-4029-90d6-9130301017a7)
maybe more attempt on kernel and coefficient choice will lead to better results.

**Comment by Scriddie** [comment]
Ah perhaps one thing to note is that the implementation in CausalDisco is using a combination of unregularized  LinearRegression (`LR`) and LarsLassoIC (`LL`) for BIC-regularization.
If you are using a regularized nonlinear regression such as KernelRidge, you may want to use the results directly without running the `LL` part. So you could set `W[cov, target]` directly to the coefficients returned by your model.

As for benchmarks, note that an empirical evaluation is always very dependent on your simulation parameters and it's often not clear how causally meaningful results of metrics like F1 and SHD are without a comparison or downstream task. It might make sense to run a nonlinear version of [random_regress](https://github.com/CausalDisco/CausalDisco/blob/main/CausalDisco/baselines.py#L35) or some other naive baseline for comparison, and to look into the evaluation metrics provided in [gajid](https://github.com/CausalDisco/gadjid) and their causal interpretation. Still, simulations can only do so much, so I would strongly recommend also thinking about it from a theoretical perspective (perhaps similarly to what we do in Section 5.1) and/or trying some real-world data (e.g. [this dataset](https://github.com/juangamella/causal-chamber), or [this dataset](https://github.com/boschresearch/causalAssembly)).

Hope this helps and best of luck with your project!
